title: Andrea's Coffee Blog
email: agiani99@hotmail.com
description: >-
  Personal blog about coffee, technology, and more by Andrea Giani.
baseurl: "/blog"
url: "https://agiani99.github.io"
twitter_username: "@agiani99"
github_username: agiani99

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
